name: Sonar Security Alert

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'src/**'
      - 'package.json'
      - 'package-lock.json'
      - '.github/workflows/sonar-security-alert.yml'


jobs:
  sonar-security-alert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Get HIGH issue count
        id: sonar
        run: |
          RESPONSE=$(curl -s -u "${{ secrets.SONAR_TOKEN }}:" \
          "https://sonarcloud.io/api/issues/search?componentKeys=Salijang_sallijang-frontend&severities=HIGH")

          HIGH_COUNT=$(echo "$RESPONSE" | jq '.total')

          echo "HIGH_COUNT=$HIGH_COUNT" >> $GITHUB_ENV

      - name: Send Slack Alert
        if: env.HIGH_COUNT != '0'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data "{
            \"text\":\"🔎 *SonarQube Security Alert*\n<@U0A5ZUZRT7A>\nRepository: sallijang-frontend\nHIGH Issues: ${HIGH_COUNT}건\n확인: https://sonarcloud.io/project/overview?id=Salijang_sallijang-frontend\"
          }" \
          $SLACK_WEBHOOK_URL
